# Generated by Django 6.1.1 on 2026-09-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('new_users', models.IntegerField(default=0, verbose_name='신규 가입')),
                ('new_posts', models.IntegerField(default=0, verbose_name='새 게시글')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('comments', models.IntegerField(default=0, verbose_name='댓글')),
                ('paid_orders', models.IntegerField(default=0, verbose_name='결제 건수')),
                ('sales', models.BigIntegerField(default=0, verbose_name='매출(원)')),
                ('chatbot_questions', models.IntegerField(default=0, verbose_name='챗봇 질문')),
                ('chatbot_unanswered', models.IntegerField(default=0, verbose_name='챗봇 미응답')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='마지막 동기화')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
