name: mobile
description: "BookStore project_4 - Flutter 모바일 클라이언트"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  dio: ^5.11.1
  flutter_secure_storage: ^11.1.1
  image_picker: ^1.2.3
  url_launcher: ^6.3.1   # 카카오페이 결제창(외부 브라우저) 이동용

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
